language: node_js
node_js:
  - 10

before_install:
  - npm i -g npm@6.9.0

install:
  - npm install

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: "suburbs-demo-app"
  cleanup: false
  region: "eu-central-1"
  local_dir: dist
  acl: public_read
  on:
    branch: add-ci